local ui = ysp.lqt.ui
local mainWindow = ui.QWidget(nil)
mainWindow:resize(900, 720)
mainWindow:setFixedSize(900,720)
mainWindow:setStyleSheet("background-color: red;")
local childWindow = ui.QWidget(mainWindow)
-- DebugMessage("width:",a,"height:",b)
childWindow:setGeometry(0,0,mainWindow:width() / 2,mainWindow:height() / 2)
childWindow:setStyleSheet("background-color: blue;")
local label = ui.QLabel(mainWindow)
label:resize(100, 200)
label:move(childWindow:x() + childWindow:width() + 10, childWindow:y())
label:setStyleSheet("background-color: yellow;color:black")
label:setText("你好，世界！")
mainWindow:show()
